# Generated by Django 5.2.14 on 2026-05-28 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hymns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hymn',
            name='category',
        ),
        migrations.DeleteModel(
            name='HymnCategory',
        ),
        migrations.AlterModelOptions(
            name='hymn',
            options={'managed': False, 'ordering': ['id'], 'verbose_name': '詩歌', 'verbose_name_plural': '詩歌'},
        ),
    ]

