# Generated by Codex on 2026-05-30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


CANONICAL_API_SCOPES = [
    {
        'scope': 'api:hymns:read',
        'label': 'Read hymn API data',
        'category': 'hymns',
        'description': 'Read hymn metadata through /api/hymns/* GET endpoints.',
    },
    {
        'scope': 'api:hymns:write',
        'label': 'Write hymn API data',
        'category': 'hymns',
        'description': 'Create, update, and delete hymn metadata.',
    },
    {
        'scope': 'api:hymns:upload',
        'label': 'Upload hymn files',
        'category': 'hymns',
        'description': 'Upload hymn files separately from metadata writes.',
    },
    {
        'scope': 'api:humnos:read',
        'label': 'Read humnos API data',
        'category': 'humnos',
        'description': 'Lookup humnos media metadata through /api/humnos/info/.',
    },
    {
        'scope': 'api:humnos:write',
        'label': 'Run humnos write workflows',
        'category': 'humnos',
        'description': 'Run humnos side-effect/download workflow.',
    },
]


def create_canonical_api_scopes(apps, schema_editor):
    ApiScope = apps.get_model('accounts', 'ApiScope')
    for scope_data in CANONICAL_API_SCOPES:
        ApiScope.objects.update_or_create(
            scope=scope_data['scope'],
            defaults={**scope_data, 'active': True},
        )


def remove_canonical_api_scopes(apps, schema_editor):
    ApiScope = apps.get_model('accounts', 'ApiScope')
    ApiScope.objects.filter(
        scope__in=[scope_data['scope'] for scope_data in CANONICAL_API_SCOPES],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_allowed_menu_items'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['scope'],
            },
        ),
        migrations.CreateModel(
            name='GroupApiScopeGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_group_api_scope_grants', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_scope_grants', to='auth.group')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_grants', to='accounts.apiscope')),
            ],
            options={
                'ordering': ['group__name', 'scope__scope'],
            },
        ),
        migrations.CreateModel(
            name='UserApiScopeGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_scope_grants', to=settings.AUTH_USER_MODEL)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_grants', to='accounts.apiscope')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_scope_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'scope__scope'],
            },
        ),
        migrations.AddConstraint(
            model_name='groupapiscopegrant',
            constraint=models.UniqueConstraint(fields=('group', 'scope'), name='unique_group_api_scope_grant'),
        ),
        migrations.AddConstraint(
            model_name='userapiscopegrant',
            constraint=models.UniqueConstraint(fields=('user', 'scope'), name='unique_user_api_scope_grant'),
        ),
        migrations.RunPython(create_canonical_api_scopes, remove_canonical_api_scopes),
    ]
