# Generated by Codex on 2026-05-30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_api_scope_storage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiScopeGrantAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('plan_version', models.PositiveIntegerField()),
                ('plan_checksum', models.CharField(max_length=64)),
                ('row_number', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=64)),
                ('dry_run', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=32)),
                ('principal_type', models.CharField(blank=True, default='', max_length=32)),
                ('principal_name', models.CharField(blank=True, default='', max_length=150)),
                ('reviewed_by', models.CharField(max_length=150)),
                ('reviewed_at', models.CharField(max_length=64)),
                ('ticket', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=255)),
                ('rollback_of', models.CharField(blank=True, default='', max_length=100)),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('planned_state', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_scope_grant_audit_events', to='auth.group')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_audit_events', to='accounts.apiscope')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_scope_grant_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='apiscopegrantaudit',
            index=models.Index(fields=['plan_checksum', 'row_number'], name='accounts_ap_plan_ch_b8f97e_idx'),
        ),
        migrations.AddIndex(
            model_name='apiscopegrantaudit',
            index=models.Index(fields=['ticket'], name='accounts_ap_ticket_4ff3b8_idx'),
        ),
        migrations.AddIndex(
            model_name='apiscopegrantaudit',
            index=models.Index(fields=['action', 'status'], name='accounts_ap_action_46a690_idx'),
        ),
    ]
